<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="dheerajv-mac" failures="1" tests="7" name="Personal" time="0.039" errors="0" timestamp="2025-10-19T17:54:26 IST">
  <testcase classname="TestNG.Test1.Demo" name="demo" time="0.001"/>
  <testcase classname="TestNG.Test1.Demo" name="secondTest" time="0.0"/>
  <testcase classname="TestNG.Test1.Demo2" name="demo2" time="0.001"/>
  <testcase classname="TestNG.Test1.Demo2" name="justToTestParameters" time="0.001"/>
  <testcase classname="TestNG.Test1.Demo4" name="LoginAPIHome" time="0.0"/>
  <testcase classname="TestNG.Test1.Demo4" name="MobileLoginHome" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNG.Test1.Demo4.MobileLoginHome(Demo4.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:132)
at java.base/java.util.concurrent.AbstractExecutorService.newTaskFor(AbstractExecutorService.java:113)
at java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:305)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- MobileLoginHome -->
  <testcase classname="TestNG.Test1.Demo4" name="WebLoginHome" time="0.0"/>
</testsuite> <!-- Personal -->
